# Generated by Django 3.2.2 on 2021-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
